networks:
  benchmark_network:
    driver: bridge
secrets:
  db_password:
    file: ./secrets/db_password.txt
services:
  embodied-ai-benchmark:
    build:
      context: .
      dockerfile: Dockerfile.prod
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G
    environment:
    - ENVIRONMENT=production
    - LOG_LEVEL=info
    - WORKERS=4
    healthcheck:
      interval: 30s
      retries: 3
      test:
      - CMD
      - python
      - -c
      - import embodied_ai_benchmark
      timeout: 10s
    ports:
    - 8000:8000
    restart: unless-stopped
    volumes:
    - benchmark_data:/app/data
    - benchmark_logs:/app/logs
  nginx:
    depends_on:
    - embodied-ai-benchmark
    image: nginx:alpine
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ssl_certs:/etc/ssl/certs
  postgres:
    environment:
    - POSTGRES_DB=embodied_ai_benchmark
    - POSTGRES_USER=benchmark_user
    - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    image: postgres:15-alpine
    restart: unless-stopped
    secrets:
    - db_password
    volumes:
    - postgres_data:/var/lib/postgresql/data
    - postgres_backup:/backup
  redis:
    image: redis:7-alpine
    ports:
    - 6379:6379
    restart: unless-stopped
    volumes:
    - redis_data:/data
version: '3.8'
volumes:
  benchmark_data: null
  benchmark_logs: null
  postgres_backup: null
  postgres_data: null
  redis_data: null
  ssl_certs: null
