apiVersion: v1
kind: ServiceAccount
metadata:
  name: embodied-ai-benchmark-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: embodied-ai-benchmark-role
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: embodied-ai-benchmark-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: embodied-ai-benchmark-role
subjects:
- kind: ServiceAccount
  name: embodied-ai-benchmark-sa
