apiVersion: v1
data:
  api-key: <base64-encoded-api-key>
  database-password: <base64-encoded-password>
  jwt-secret: <base64-encoded-jwt-secret>
kind: Secret
metadata:
  name: embodied-ai-benchmark-secrets
type: Opaque
